apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: awx-root
  namespace: awx
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: awx.homelab.lan
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: awx-server-service
                port:
                  number: 80
