version: 3

images:
  base_image:
    name: registry.access.redhat.com/ubi9/python-312:latest

dependencies:
  ansible_core:
    package_pip: ansible-core>=2.15.0
  ansible_runner:
    package_pip: ansible-runner
  galaxy:
    collections:
      - name: community.general
  python:
    - gitlabform
    - python-gitlab
  system:
    - git-core
    - gcc
    - python3-pip

additional_build_steps:
  prepend_builder:
    # This stage is where the 'assemble' script actually runs
    - RUN dnf install -y python3-pip
    - RUN python3 -m pip install --upgrade pip
    - RUN python3 -m pip install gitlabform