apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: awxdb-ha
  namespace: awx
spec:
  postgresVersion: 16
  instances:
    - name: inst
      replicas: 3
      dataVolumeClaimSpec:
        storageClassName: longhorn-ha-any
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 50Gi
  backups:
    pgbackrest:
      global:
        repo1-retention-full: "7"
        repo1-retention-diff: "7"
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              storageClassName: longhorn-backups-dedicated
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 150Gi
  users:
    - name: awxdb-ha
      databases: ["awxdb-ha"]
      options: "SUPERUSER"
