---
- name: GitLab Configuration as Code - Direct Membership
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    gitlab_url: "http://gitlab.homelab.lan/"
    target_scope: "test-group/test-project"

  tasks:
    - name: Generate GitLabForm Configuration File
      ansible.builtin.copy:
        dest: /tmp/gitlab_config.yml
        content: |
          config_version: 4
          api_version: 4

          gitlab:
            url: "{{ gitlab_url }}"
            token: "{{ lookup('env', 'GITLAB_TOKEN') }}"

          projects_and_groups:
            "{{ target_scope }}":
              members:
                users:
                  testuser:
                    access_level: Maintainer
                    expires_at: 2026-04-19
                enforce: true
                keep_bots: true

    - name: Cat Configuration for Verification
      ansible.builtin.command: cat /tmp/gitlab_config.yml
      register: cat_output

    - name: Show Config
      ansible.builtin.debug:
        var: cat_output.stdout_lines

    - name: Run GitLabForm
      ansible.builtin.shell: "gitlabform -c /tmp/gitlab_config.yml -v {{ target_scope }}"
      # environment:
      #   GITLAB_URL: "{{ gitlab_url }}"
      #   GITLAB_TOKEN: "{{ lookup('env', 'GITLAB_TOKEN') }}"
      #   PATH: "/runner/.local/bin:/usr/local/bin:/usr/bin:{{ ansible_env.PATH | default('') }}"
      # register: gitlabform_result

    - name: Display GitLab Output
      ansible.builtin.debug:
        var: gitlabform_result.stderr_lines